# Generated by Django 4.2.6 on 2023-10-25 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autosalons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.FloatField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_discounts', to='autosalons.carmodel')),
            ],
        ),
        migrations.CreateModel(
            name='History_of_Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
                ('car', models.ManyToManyField(related_name='History_of_Sales', to='autosalons.carmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year_founded', models.PositiveIntegerField()),
                ('num_customers', models.IntegerField()),
                ('cars', models.ManyToManyField(related_name='suppliers_of_car', to='autosalons.carmodel')),
                ('discounts', models.ManyToManyField(related_name='suppliers', to='suppliers.discount')),
                ('sales_history', models.ManyToManyField(related_name='suppliers_history', to='suppliers.history_of_sales')),
            ],
        ),
    ]
