# Generated by Django 4.2.6 on 2023-10-25 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autosalons', '0001_initial'),
        ('customers', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='suppliers',
            field=models.ManyToManyField(related_name='cars_in_supplier', to='suppliers.supplier'),
        ),
        migrations.AddField(
            model_name='autosalon',
            name='car_model',
            field=models.ManyToManyField(related_name='autosalons', to='autosalons.carmodel'),
        ),
        migrations.AddField(
            model_name='autosalon',
            name='dicount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autosalons.discount'),
        ),
        migrations.AddField(
            model_name='autosalon',
            name='sales_history',
            field=models.ManyToManyField(blank=True, related_name='autosalons', to='autosalons.salehistory'),
        ),
        migrations.AddField(
            model_name='autosalon',
            name='unique_customers',
            field=models.ManyToManyField(blank=True, related_name='autosalons', to='customers.customer'),
        ),
    ]
