# Generated by Django 4.2.6 on 2023-11-11 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autosalons', '0001_initial'),
        ('suppliers', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierspecificationrelationship',
            name='discount_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_suppliers_of_specifications', to='suppliers.supplierdiscount'),
        ),
        migrations.AddField(
            model_name='supplierspecificationrelationship',
            name='specification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_specification_prices', to='autosalons.specification'),
        ),
        migrations.AddField(
            model_name='supplierspecificationrelationship',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_specification_prices', to='suppliers.supplier'),
        ),
        migrations.AddField(
            model_name='specification',
            name='supplier',
            field=models.ManyToManyField(related_name='supplier_specifications', through='autosalons.SupplierSpecificationRelationship', to='suppliers.supplier'),
        ),
        migrations.AddField(
            model_name='showroomhistory',
            name='car',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saled_cars', to='autosalons.car'),
        ),
        migrations.AddField(
            model_name='showroomhistory',
            name='showroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showroom_histories', to='autosalons.showroom'),
        ),
        migrations.AddField(
            model_name='showroomhistory',
            name='unique_customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_histories', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='showroomcarrelationship',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='autosalons.car'),
        ),
        migrations.AddField(
            model_name='showroomcarrelationship',
            name='discount_showroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars_showroom_discount', to='autosalons.showroomdiscount'),
        ),
        migrations.AddField(
            model_name='showroomcarrelationship',
            name='showroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autosalons.showroom'),
        ),
        migrations.AddField(
            model_name='showroom',
            name='car',
            field=models.ManyToManyField(blank=True, related_name='showrooms', through='autosalons.ShowroomCarRelationship', to='autosalons.car'),
        ),
        migrations.AddField(
            model_name='showroom',
            name='discount_showroom',
            field=models.ManyToManyField(blank=True, related_name='showrooms_discount', to='autosalons.showroomdiscount'),
        ),
        migrations.AddField(
            model_name='showroom',
            name='specifications',
            field=models.ManyToManyField(blank=True, related_name='showrooms_specification', to='autosalons.specification'),
        ),
        migrations.AddField(
            model_name='car',
            name='specification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_specification', to='autosalons.specification'),
        ),
    ]
