# Generated by Django 4.2.6 on 2023-11-01 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('suppliers', '0001_initial'),
        ('autosalons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier_specification_price',
            name='discount_supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_supplier', to='suppliers.supplier_discount'),
        ),
        migrations.AddField(
            model_name='supplier_specification_price',
            name='specification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_specification_prices', to='autosalons.specification'),
        ),
        migrations.AddField(
            model_name='supplier_specification_price',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_specification_prices', to='suppliers.supplier'),
        ),
        migrations.AddField(
            model_name='specification',
            name='supplier',
            field=models.ManyToManyField(related_name='specification_suppliers', through='autosalons.Supplier_Specification_price', to='suppliers.supplier'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='specification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_specification', to='autosalons.specification'),
        ),
        migrations.AddField(
            model_name='carinautosalon',
            name='autosalon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autosalons.autosalon'),
        ),
        migrations.AddField(
            model_name='carinautosalon',
            name='car_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autosalons.carmodel'),
        ),
        migrations.AddField(
            model_name='carinautosalon',
            name='discount_autosalon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars_autosalon_discount', to='autosalons.discount_autosalon'),
        ),
        migrations.AddField(
            model_name='autosalon_history',
            name='autosalon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autosalon_histories', to='autosalons.autosalon'),
        ),
        migrations.AddField(
            model_name='autosalon_history',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saled_cars', to='autosalons.carmodel'),
        ),
        migrations.AddField(
            model_name='autosalon_history',
            name='unique_customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_histories', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='autosalon',
            name='car',
            field=models.ManyToManyField(blank=True, related_name='autosalons', through='autosalons.CarInAutosalon', to='autosalons.carmodel'),
        ),
        migrations.AddField(
            model_name='autosalon',
            name='discount_autosalon',
            field=models.ManyToManyField(blank=True, related_name='autosalons_discount', to='autosalons.discount_autosalon'),
        ),
        migrations.AddField(
            model_name='autosalon',
            name='specifications',
            field=models.ManyToManyField(blank=True, related_name='autosalons_specification', to='autosalons.specification'),
        ),
    ]
