# Generated by Django 4.2.6 on 2023-11-29 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autosalons', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showroomcarrelationship',
            name='showroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_relationships', to='autosalons.showroom'),
        ),
    ]
