# Generated by Django 4.2.6 on 2023-10-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autosalons', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='autosolons',
            field=models.ManyToManyField(null=True, related_name='cars_in_autosalon', to='autosalons.autosalon'),
        ),
    ]
