# Generated by Django 4.2.6 on 2023-12-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
